from numpy import ndarray, dtype, float64
from ctypes import c_char
from typing import Any, Literal
from mmap import mmap


type fb_t = mmap | ndarray[tuple[Any, ...], dtype[float64]] | ndarray[tuple[Any, ...], dtype]
def draw_line(fb: fb_t, width: int, x0: int, y0: int, x1: int, y1: int, color: int) -> None: ...
def draw_lines(fb: fb_t, width: int, points: list[tuple[int, int]], color: int) -> None: ...

def draw_rect(fb: fb_t, width: int, height: int, x: int, y: int, w: int, h: int, color: int) -> None: ...

def draw_circle(fb: fb_t, width: int, cx: int, cy: int, radius: int, thickness: int, color: int) -> None: ...
def draw_filled_circle(fb: fb_t, width: int, cx: int, cy: int, radius: int, color: int) -> None: ...

def draw_char(fb: fb_t, width: int, x: int, y: int, character: c_char, clor: int) -> None: ...
def draw_char_48(fb: fb_t, width: int, x: int,  y: int, character: c_char, color: int) -> None: ...
def draw_char_96(fb: fb_t, width: int, x: int,  y: int, character: c_char, color: int) -> None: ...
