from numpy import ndarray, dtype, float64
from mmap import mmap
from typing import Any


type fb_t = mmap | ndarray[tuple[Any, ...], dtype[float64]] | ndarray[tuple[Any, ...], dtype
def draw_line(fb: fb_t, width: int, x0: int, y0: int, x1: int, y1: int, color: int) -> None: ...
def draw_lines(fb: fb_t, width: int, points: list[tuple[int, int]], color: int) -> None: ...

def draw_circle(fb: fb_t, width: int, cx: int, cy: int, radius: int, color: int) -> None: ...
def draw_filled_circle(fb: fb_t, width: int, cx: int, cy: int, radius: int, color: int) -> None: ...
